### ISSUE TITLE
System.Exception: No new interface could be found after devcon finished.

### ISSUE THREAD

**Issue by icnocop** [Wootness/LoopbackNET#2]
Hi.

If devcon.exe doesn't exist in the path, the following exception is thrown:
`System.Exception: No new interface could be found after devcon finished.`.

I expected a more meaningful error like "FileNotFoundException: devcon.exe not found in any of the search paths."

Thank you.

**Comment by theXappy** [comment]
Hi Rami
Thank you for your interest in my project.
Unfortunately I don't have any free time to add this fix, although it might be a good idea to throw such an exception.

If you are willing to compose a fix and send a PR I might merge it.
Alternatively, feel free to fork my repo and make any changes you desired. The code base is not huge and I bet you can find where to include your changes rather easily.
