### ISSUE TITLE
Ability to set static IPv4 address

### ISSUE THREAD

**Issue by icnocop** [Wootness/LoopbackNET#3]
Hi.

I'd like to request the ability to set a static IPv4 address to the loopback adapter.

Thank you.

**Comment by theXappy** [comment]
I'm don't think this falls in the scope of Loopback.NET.
Such a change can also be relevant to other interfaces (non-loopback ones) so perhaps a different utility should do that.

If you have any reason to believe a *loopback specific logic* is required in that case (and hence should be included in Loopback.NET), I'm open to hear it.

For now, I'm closing this issue.
